path_to_input: '/home/iantsen/hecktor/data/hecktor_test/hecktor_nii_test/'  # directory with images
path_to_bb: '/home/iantsen/hecktor/data/hecktor_test/bbox_test.csv'  # file with bounding box coordinates
path_to_output: '/home/iantsen/hecktor/data/hecktor_test/hecktor_nii_resampled/'  # directory to save resampled images
is_mask_available: false  # if `true`, masks will be preprocessed. Use `false`, if masks are unavailable
verbose: false  # if `true`, the progress bar will be shown