path_to_input: 'C:/inserm/hecktor/hecktor_train/hecktor_nii/'  # a directory with images
path_to_bb: 'C:/inserm/hecktor/hecktor_train/bbox.csv'  # a file with a bounding box coordinates
path_to_output: 'C:/inserm/hecktor/hecktor_train/hecktor_nii_resampled/'  # a directory to save resampled images
is_mask_available: true  # if `true`, masks will be preprocessed. Use `false`, if masks are unavailable